### PR TITLE
fix(conditionalwrap): component should always return one child

### PR DESCRIPTION
**Pull request by RedTn**
Closes https://github.com/pradel/react-responsive-modal/issues/229

### CODE REVIEW

**Comment by pradel** [comment]
The problem with that approach is that it will create a new div which might break the layout for some users 🤔

**Comment by RedTn** [comment]
> The problem with that approach is that it will create a new div which might break the layout for some users 🤔

Are you aware if Fragments written in 16 and bundled is compatible with 15? If not I could just do a simple if-else in the modal

**Comment by pradel** [comment]
Hum I am not sure but I don't think it's possible unfortunately.
A simple if else sounds good 👍

**Comment by RedTn** [comment]
Nevermind, if-else will still require me to return array. I realized that I could just encapsulate the parent div inside the conditional wrap and it should work!

**Comment by RedTn** [comment]
Something is wrong with the centering when focusTrapped is true, I will need to take a look at it

**Comment by pradel** [comment]
Published as v3.5.1 thanks for the fix @RedTn !

**Pull request merged**
