### PR TITLE
Add tab index to close icon

### PR DESCRIPTION
**Pull request by peterlazzarino**
PR for issue #36 @pradel I'd like your thoughts on this. React currently has a known issue in production that is resolved in a beta branch that prevents SVG elements from properly rendering the tabindex attribute without camel case which prevents it from working currently. 

https://github.com/facebook/react/issues/10987

Tab index here is set to 0 so it doesn't interfere with any tabindex attributes set on modal content such as forms, etc. The only potential issue I can see is that since the close button is first in the element list, it will be the first tab option before anything in the modal. This could be resolved by moving the close button below the body content since it is absolute positioned.

### CODE REVIEW

**Comment by pradel** [comment]
Hum I am not an expert in tabIndex so I can't think about other side effect
any opinion @artemjackson?

Could you move the close icon please? I will try after that :)

**Comment by peterlazzarino** [comment]
@pradel all set, just moved it and it's working great for me. I'm able to tab to X after tabbing through form content.

**Comment by artemjackson** [comment]
@pradel @peterlazzarino 
I would recommend to wrap SVG with an `button`, cuz `button` catches "Tab"-ing by default and emits `click` event on `space` or `enter` hit.

**Comment by pradel** [comment]
@artemjackson we should definitely wrap it with a button will be easier you are right. @peterlazzarino does that looks good to you?

**Comment by peterlazzarino** [comment]
@pradel I was playing around with this yesterday however that button would have to be the one that is styled absolute, top, right, etc instead of the SVG. The closeIcon class would no longer behave as it does now resulting in some potentially breaking changes for consumers. This is also complicated by the SVG size prop that is passed in to the component.

I was thinking a good solution to keep as much backwards compatibility as possible would be to wrap the SVG with a button that has a tabIndex and a new closeButton class style that has the absolute positioning. The user could override the closeIcon and style it like they can now and also still pass the height and width for the SVG but to move it around they'd have to style the button.

What do you think?

**Comment by pradel** [comment]
@peterlazzarino would be great to keep backward compatibility if possible
Your solution seems like a good one :)

**Comment by pradel** [comment]
@peterlazzarino does that looks good to you?
I will also fix other bugs and release as a major version `3.0.0`

**Pull request merged**
